services:
  php:
    build: .
    image: hyperf-database-sqlserver-php:3.x
    volumes:
      - ./:/opt/www
    tty: true
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=XTguSD7of8yx%G%r
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"